run:
  timeout: 5m

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 12
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  gofumpt:
    extra-rules: true
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/instana/testify"
            desc: not allowed
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package
  funlen:
    lines: -1
    statements: 40
  godox:
    keywords:
      - FIXME
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - sloppyReassign
      - rangeValCopy
      - octalLiteral
      - paramTypeCombine # already handle by gofumpt.extra-rules
    settings:
      hugeParam:
        sizeThreshold: 100
  forbidigo:
    forbid:
      - '^print(ln)?$'
      - '^spew\.Print(f|ln)?$'
      - '^spew\.Dump$'
  gomoddirectives:
    replace-allow-list:
      - github.com/abbot/go-http-auth
      - github.com/go-check/check
      - github.com/gorilla/mux
      - github.com/mailgun/minheap
      - github.com/mailgun/multibuf
      - github.com/jaguilar/vt100
  gosec:
    excludes:
      - G204 # Subprocess launched with a potential tainted input or cmd arguments
      - G301 # Expect directory permissions to be 0750 or less
      - G306 # Expect WriteFile permissions to be 0600 or less

linters:
  enable-all: true
  disable:
    - gomnd # deprecated
    - execinquery # deprecated
    - exportloopref # deprecated
    - sqlclosecheck # not relevant (SQL)
    - rowserrcheck # not relevant (SQL)
    - cyclop # duplicate of gocyclo
    - lll
    - dupl
    - prealloc
    - wsl
    - nlreturn
    - mnd
    - testpackage
    - paralleltest
    - tparallel
    - err113
    - wrapcheck
    - exhaustive
    - exhaustruct
    - varnamelen
    - nilnil

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - 'ST1000: at least one file in a package should have a package comment'
    - 'package-comments: should have a package comment'
  exclude-rules:
    - path: cmd/
      linters:
        - gochecknoglobals
        - gochecknoinits

output:
  show-stats: true
  sort-results: true
  sort-order:
    - linter
    - file
