version: 2
project_name: traefik-certs-dumper

builds:
  - binary: traefik-certs-dumper
    ldflags:
      - -s -w -X github.com/ldez/traefik-certs-dumper/cmd.version={{.Version}} -X github.com/ldez/traefik-certs-dumper/cmd.commit={{.ShortCommit}} -X github.com/ldez/traefik-certs-dumper/cmd.date={{.Date}}
    env:
      - GO111MODULE=on
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 7
      - 6
      - 5

    ignore:
      - goos: darwin
        goarch: 386

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^chore:'
      - '^chore\(deps\):'
      - '^test:'
      - '^tests:'

archives:
  - id: tcd
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

docker_manifests:
  - name_template: 'ldez/traefik-certs-dumper:{{ .Tag }}'
    image_templates:
      - 'ldez/traefik-certs-dumper:{{ .Tag }}-amd64'
      - 'ldez/traefik-certs-dumper:{{ .Tag }}-arm64'
      - 'ldez/traefik-certs-dumper:{{ .Tag }}-armv7'
  - name_template: 'ldez/traefik-certs-dumper:latest'
    image_templates:
      - 'ldez/traefik-certs-dumper:{{ .Tag }}-amd64'
      - 'ldez/traefik-certs-dumper:{{ .Tag }}-arm64'
      - 'ldez/traefik-certs-dumper:{{ .Tag }}-armv7'
  - name_template: 'ldez/traefik-certs-dumper:v{{ .Major }}.{{ .Minor }}'
    image_templates:
      - 'ldez/traefik-certs-dumper:v{{ .Major }}.{{ .Minor }}-amd64'
      - 'ldez/traefik-certs-dumper:v{{ .Major }}.{{ .Minor }}-arm64'
      - 'ldez/traefik-certs-dumper:v{{ .Major }}.{{ .Minor }}-armv7'

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: buildx.Dockerfile
    image_templates:
      - 'ldez/traefik-certs-dumper:latest-amd64'
      - 'ldez/traefik-certs-dumper:{{ .Tag }}-amd64'
      - 'ldez/traefik-certs-dumper:v{{ .Major }}.{{ .Minor }}-amd64'
    build_flag_templates:
      - '--pull'
      # https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
      - '--label=org.opencontainers.image.title={{.ProjectName}}'
      - '--label=org.opencontainers.image.description=Dump ACME data from Traefik to certificates'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--label=org.opencontainers.image.url={{.GitURL}}'
      - '--label=org.opencontainers.image.documentation=https://github.com/ldez/traefik-certs-dumper'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--platform=linux/amd64'

  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: buildx.Dockerfile
    image_templates:
      - 'ldez/traefik-certs-dumper:latest-arm64'
      - 'ldez/traefik-certs-dumper:latest-arm.v8' # only for compatibility with Seihon
      - 'ldez/traefik-certs-dumper:{{ .Tag }}-arm64'
      - 'ldez/traefik-certs-dumper:{{ .Tag }}-arm.v8' # only for compatibility with Seihon
      - 'ldez/traefik-certs-dumper:v{{ .Major }}.{{ .Minor }}-arm64'
    build_flag_templates:
      - '--pull'
      # https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
      - '--label=org.opencontainers.image.title={{.ProjectName}}'
      - '--label=org.opencontainers.image.description=Dump ACME data from Traefik to certificates'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--label=org.opencontainers.image.url={{.GitURL}}'
      - '--label=org.opencontainers.image.documentation=https://github.com/ldez/traefik-certs-dumper'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--platform=linux/arm64'

  - use: buildx
    goos: linux
    goarch: arm
    goarm: '7'
    dockerfile: buildx.Dockerfile
    image_templates:
      - 'ldez/traefik-certs-dumper:latest-armv7'
      - 'ldez/traefik-certs-dumper:latest-arm.v7' # only for compatibility with Seihon
      - 'ldez/traefik-certs-dumper:{{ .Tag }}-armv7'
      - 'ldez/traefik-certs-dumper:{{ .Tag }}-arm.v7' # only for compatibility with Seihon
      - 'ldez/traefik-certs-dumper:v{{ .Major }}.{{ .Minor }}-armv7'
    build_flag_templates:
      - '--pull'
      # https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
      - '--label=org.opencontainers.image.title={{.ProjectName}}'
      - '--label=org.opencontainers.image.description=Dump ACME data from Traefik to certificates'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--label=org.opencontainers.image.url={{.GitURL}}'
      - '--label=org.opencontainers.image.documentation=https://github.com/ldez/traefik-certs-dumper'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--platform=linux/arm/v7'
